#!/usr/bin/env python
"""Phase 2 ML training: read the JS-built feature frame, train the starter model set,
export each to ONNX (ir_version=9 for the C++ onnxruntime 1.17.1 ceiling), and write the
shared feature_config.yaml + metadata.json that the serving layer (Phase 3 C++) consumes.

Starter models (all predict the 3-class N-bar forward label {0=down, 1=flat, 2=up}):
  - xgboost_v1       : gradient-boosted trees over ALL features
  - logistic_v1      : StandardScaler -> multinomial logistic over ALL features
  - regime_classifier: StandardScaler -> logistic over CROSS-FAMILY features only
                       (regime_*_mom + xf_corr_*) — the cross-family signal in one place.

No train/serve skew: missing cells are filled with TRAIN-split medians, and those medians
(+ the exact feature column order per model) are written to feature_config.yaml so the
serving layer fills/orders inputs identically. Scaling for the linear models is baked INTO
the ONNX graph (Pipeline), so the only external serving contract is the median fill.

Run with the dedicated env:  .venv_ml/Scripts/python.exe scripts/ml/train.py
"""
import json
import os
import sys

import numpy as np
import pandas as pd
import onnx
import onnxruntime as ort
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from skl2onnx import convert_sklearn
from skl2onnx.common.data_types import FloatTensorType
from xgboost import XGBClassifier
from onnxmltools.convert import convert_xgboost
from onnxmltools.convert.common.data_types import FloatTensorType as MlFloatTensorType

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
CSV_PATH = os.path.join(REPO_ROOT, "storage", "data", "ml", "feature_frame.csv")
MODELS_DIR = os.path.join(REPO_ROOT, "storage", "models")
IR_VERSION = 9          # onnxruntime 1.17.1 (C++) caps model IR version at 9
TARGET_OPSET = 15
LABEL_CLASSES = {0: "down", 1: "flat", 2: "up"}
NON_FEATURE = {"symbol", "as_of", "label_class", "label_fwd_return"}


def load_frame():
    df = pd.read_csv(CSV_PATH)
    df = df[df["label_class"].notna()].copy()
    df["label_class"] = df["label_class"].astype(int)
    # Global time-ordered split (no shuffle) to avoid using the future to predict the past.
    df = df.sort_values("as_of").reset_index(drop=True)
    feature_cols = [c for c in df.columns if c not in NON_FEATURE]
    cross_family = [c for c in feature_cols if c.startswith("regime_") or c.startswith("xf_corr_")]
    return df, feature_cols, cross_family


def split_xy(df, cols, medians):
    X = df[cols].apply(pd.to_numeric, errors="coerce")
    X = X.fillna(medians).fillna(0.0)
    return X.to_numpy(dtype=np.float32), df["label_class"].to_numpy(dtype=np.int64)


def majority_baseline(y_train, y_hold):
    maj = int(pd.Series(y_train).mode().iloc[0])
    return float((y_hold == maj).mean()), maj


def to_onnx_sklearn(pipe, n_features):
    onx = convert_sklearn(
        pipe,
        initial_types=[("input", FloatTensorType([None, n_features]))],
        target_opset=TARGET_OPSET,
        options={id(pipe): {"zipmap": False}},
    )
    onx.ir_version = IR_VERSION
    return onx


def to_onnx_xgb(model, n_features):
    onx = convert_xgboost(
        model,
        initial_types=[("input", MlFloatTensorType([None, n_features]))],
        target_opset=TARGET_OPSET,
    )
    onx.ir_version = IR_VERSION
    return onx


def verify_onnx(path, X_hold, y_hold):
    """Load via onnxruntime, run the holdout, return (accuracy, ir_version, opset)."""
    model = onnx.load(path)
    sess = ort.InferenceSession(path, providers=["CPUExecutionProvider"])
    out = sess.run(None, {"input": X_hold})
    # First output is the predicted label tensor for every converter we use here.
    pred = np.asarray(out[0]).reshape(-1).astype(np.int64)
    acc = float((pred == y_hold).mean())
    opset = max(op.version for op in model.opset_import)
    return acc, int(model.ir_version), int(opset)


def write_serving_manifest(path, feature_cols, medians, models_meta):
    """Whitespace-delimited manifest the C++ inference path reads (no JSON/YAML parser in C++).
      COL   <name> <train_median>
      MODEL <name> <models/...onnx> <input_set> <n_features>
    Column names are identifiers and paths/values have no spaces, so split-on-whitespace is safe."""
    lines = ["# serving manifest — generated by scripts/ml/train.py",
             "# COL <name> <median> ; MODEL <name> <path> <input_set> <n_features>"]
    for c in feature_cols:
        lines.append(f"COL {c} {medians[c]:.10g}")
    for m in models_meta:
        lines.append(f"MODEL {m['name']} {m['path']} {m['input_set']} {m['n_features']}")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


def write_feature_config(path, feature_cols, cross_family, medians, models_meta):
    lines = ["# Generated by scripts/ml/train.py — shared train/serve feature contract.",
             "# Serving: fill missing cells with `medians[col]`, order inputs as `feature_columns`.",
             f"label_classes: {{0: down, 1: flat, 2: up}}",
             "imputation: median",
             "feature_columns:"]
    for c in feature_cols:
        lines.append(f"  - {c}")
    lines.append("cross_family_columns:")
    for c in cross_family:
        lines.append(f"  - {c}")
    lines.append("medians:")
    for c in feature_cols:
        lines.append(f"  {c}: {medians[c]:.10g}")
    lines.append("models:")
    for m in models_meta:
        lines.append(f"  {m['name']}:")
        lines.append(f"    input: {m['input_set']}")
        lines.append(f"    n_features: {m['n_features']}")
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


def main():
    if not os.path.exists(CSV_PATH):
        sys.exit(f"feature frame not found: {CSV_PATH} (run `sovereign ml dump` first)")
    os.makedirs(MODELS_DIR, exist_ok=True)

    df, feature_cols, cross_family = load_frame()
    n = len(df)
    cut = int(n * 0.8)
    train_df, hold_df = df.iloc[:cut], df.iloc[cut:]

    # Train-split medians per feature column (the shared imputation contract).
    train_num = train_df[feature_cols].apply(pd.to_numeric, errors="coerce")
    medians = train_num.median()
    medians = {c: (float(medians[c]) if np.isfinite(medians[c]) else 0.0) for c in feature_cols}
    medians_s = pd.Series(medians)

    Xtr_all, ytr = split_xy(train_df, feature_cols, medians_s)
    Xho_all, yho = split_xy(hold_df, feature_cols, medians_s)
    Xtr_cf, _ = split_xy(train_df, cross_family, medians_s)
    Xho_cf, _ = split_xy(hold_df, cross_family, medians_s)

    base_acc, maj = majority_baseline(ytr, yho)
    print(f"rows={n} train={len(train_df)} holdout={len(hold_df)} "
          f"features_all={len(feature_cols)} cross_family={len(cross_family)}")
    print(f"majority baseline class={maj} ({LABEL_CLASSES[maj]}) holdout_acc={base_acc:.4f}\n")

    specs = [
        ("xgboost_v1", "all", feature_cols, Xtr_all, Xho_all, "xgb"),
        ("logistic_v1", "all", feature_cols, Xtr_all, Xho_all, "linear"),
        ("regime_classifier", "cross_family", cross_family, Xtr_cf, Xho_cf, "linear"),
    ]

    models_meta = []
    for name, input_set, cols, Xtr, Xho, kind in specs:
        if kind == "xgb":
            clf = XGBClassifier(
                n_estimators=200, max_depth=5, learning_rate=0.05,
                objective="multi:softprob", num_class=3, subsample=0.9,
                colsample_bytree=0.9, eval_metric="mlogloss", tree_method="hist",
            )
            clf.fit(Xtr, ytr)
            onx = to_onnx_xgb(clf, len(cols))
        else:
            clf = Pipeline([("scaler", StandardScaler()),
                            ("logreg", LogisticRegression(max_iter=2000, C=1.0))])
            clf.fit(Xtr, ytr)
            onx = to_onnx_sklearn(clf, len(cols))

        path = os.path.join(MODELS_DIR, f"{name}.onnx")
        onnx.save(onx, path)
        acc, ir, opset = verify_onnx(path, Xho, yho)
        lift = acc - base_acc
        print(f"{name:18s} input={input_set:12s} acc={acc:.4f} "
              f"lift={lift:+.4f} ir={ir} opset={opset} -> {os.path.relpath(path, REPO_ROOT)}")
        assert ir == IR_VERSION, f"{name}: ir_version {ir} != {IR_VERSION}"
        models_meta.append({
            "name": name, "path": f"models/{name}.onnx", "input_set": input_set,
            "n_features": len(cols), "holdout_accuracy": round(acc, 4),
            "baseline_accuracy": round(base_acc, 4), "lift_vs_baseline": round(lift, 4),
            "ir_version": ir, "opset": opset, "beats_baseline": bool(acc > base_acc),
        })

    fc_path = os.path.join(MODELS_DIR, "feature_config.yaml")
    write_feature_config(fc_path, feature_cols, cross_family, medians, models_meta)
    manifest_path = os.path.join(MODELS_DIR, "serving_manifest.txt")
    write_serving_manifest(manifest_path, feature_cols, medians, models_meta)

    meta = {
        "schema": "sovereign.ml.metadata/v2",
        "generated_by": "scripts/ml/train.py",
        "feature_config": "models/feature_config.yaml",
        "label_classes": LABEL_CLASSES,
        "horizon_note": "3-class N-bar forward direction; see feature_frame.meta.json for horizon/deadzone",
        "dataset": {"rows": n, "train": len(train_df), "holdout": len(hold_df),
                    "feature_columns": len(feature_cols)},
        "models": [
            {**m, "status": "trained_prototype",
             "promoted": bool(m["beats_baseline"]),
             "feature_config": "models/feature_config.yaml"}
            for m in models_meta
        ],
    }
    with open(os.path.join(MODELS_DIR, "metadata.json"), "w", encoding="utf-8") as f:
        json.dump(meta, f, indent=2)

    print(f"\nwrote {fc_path}")
    print(f"wrote {manifest_path}")
    print(f"wrote {os.path.join(MODELS_DIR, 'metadata.json')}")
    print("promoted:", [m["name"] for m in models_meta if m["beats_baseline"]])


if __name__ == "__main__":
    main()
