# Constants for Polymarket HFT

# Order sides
BUY = "BUY"
SELL = "SELL"

# Market outcomes
YES = "YES"
NO = "NO"

# Signal types
SIGNAL_ARB = "ARB"
SIGNAL_REVERSION = "REVERSION"
SIGNAL_LAG = "LAG"
SIGNAL_DIP = "DIP"
SIGNAL_OPTIMISM_TAX = "OPTIMISM_TAX"

# Order types
MARKET_ORDER = "MARKET"
LIMIT_ORDER = "LIMIT"

# WebSocket channels
CHANNEL_BOOK = "book"
CHANNEL_PRICE = "price"
CHANNEL_TRADE = "trade"

# Timeframes
TIMEFRAME_1M = "1m"
TIMEFRAME_5M = "5m"
TIMEFRAME_15M = "15m"

# Status
STATUS_CONNECTED = "CONNECTED"
STATUS_DISCONNECTED = "DISCONNECTED"
STATUS_RECONNECTING = "RECONNECTING"

# Constraints
MAX_CANDLE_STREAK = 3
STREAK_REVERSION_PROB = 0.72
PRICE_DROP_THRESHOLD = 0.20
PRICE_LAG_THRESHOLD = 0.015  # 1.5%
